### ISSUE TITLE
Bronze DLT not used in subsequent query

### ISSUE THREAD

**Issue by lucianmoldovanu** [rxhl/dlt-databricks#1]
Hi! I was just reading through your Medium article and following the code. Any reason why, in the transformations, you create bronze DLT's (games_raw, teams_raw, game_opponents_raw, game_scores_raw_) but then you don't use them in your subsequent query?

**Comment by rxhl** [comment]
Hey Lucian, the bronze zone tables are supposed to persist the raw data "as-is" in case you need to go back and use it later e.g., audit, recreate silver and gold tables. For actual data analysis and BI, you'd most likely use silver and gold tables.
